Add support for immediate tiering
minio/minio-go pull request #1559
Opened 2021-09-27 20:51 UTC by krisis

This change adds support for Transition/NoncurrentVersionTransition action to allow zero days, i.e immediate tiering.

2021-09-28 18:59 UTC, poornas requested changes

2021-09-28 18:59 UTC, poornas commented on pkg/lifecycle/lifecycle.go
> +	NoncurrentDays ExpirationDays `xml:"NoncurrentDays" json:"NoncurrentDays"`
`StorageClass` should not have `omitempty` here

2021-09-28 18:59 UTC, poornas commented on pkg/lifecycle/lifecycle.go
> +	Days         ExpirationDays `xml:"Days" json:"Days"`
StorageClass is not optional - so should not be `omitempty`. Otherwise the IsNull checks while marshaling make no sense

2021-09-28 19:26 UTC, poornas commented on pkg/lifecycle/lifecycle.go
> +		Days         *ExpirationDays `json:"Days"`
This cannot be `omitempty` - either transition-days or transition-date will be specified

2021-09-28 20:42 UTC, poornas approved these changes
LGTM

2021-09-29 10:16 UTC, vadmeste commented
@krisis how to test this exactly ?

2021-10-03 13:32 UTC, vadmeste approved these changes
LGTM

2021-10-03 16:19 UTC, harshavardhana approved these changes

2021-10-03 16:19 UTC, merged