Sync ignored v4 presign headers
minio/minio-go pull request #1630
Opened 2022-04-01 08:53 UTC by superseb

https://github.com/minio/minio-go/issues/1629

2022-04-09 23:12 UTC, harshavardhana requested changes

2022-04-09 23:12 UTC, harshavardhana commented on pkg/signer/request-signature-v4.go
> +	"Content-MD5":          true,
This is not an ignored header..

2022-04-09 23:12 UTC, harshavardhana commented on pkg/signer/request-signature-v4.go
> +	"X-Amz-Content-SHA256": true,
This is not an ignored header.

2022-04-09 23:12 UTC, harshavardhana commented on pkg/signer/request-signature-v4.go
> +	"X-Amz-Date":           true,
This is not an ignored header.

2022-04-09 23:12 UTC, harshavardhana commented on pkg/signer/request-signature-v4.go
> +	"X-Amz-Security-Token": true,
This is not an ignored header.

2022-04-09 23:14 UTC, harshavardhana commented
All you need to add is `accept-encoding` to the list.

2022-04-11 07:15 UTC, superseb commented
@harshavardhana Thanks! I have synced the list from https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/Signer.java#L58, let me know if you still just want to add `accept-encoding`.

2022-04-11 09:40 UTC, harshavardhana commented
> @harshavardhana Thanks! I have synced the list from https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/Signer.java#L58, let me know if you still just want to add `accept-encoding`.

ignoring those headers is a bug in minio-java @superseb please fix the PR here the way I asked.

2022-04-13 23:20 UTC, harshavardhana commented
Please resubmit once the relevant changes are done closing.

2022-04-13 23:20 UTC, closed without merging