Add date if not present and there is no "X-Amz-Date"
minio/minio-go pull request #1685
Opened 2022-08-02 07:21 UTC by zhutianhao

Upon receiving the request, Amazon S3 re-creates the string to sign using information in the Authorization header and the date header. It then verifies with authentication service the signatures match. The request date can be specified by using either the HTTP Date or the x-amz-date header. If both headers are present, x-amz-date takes precedence.

2022-08-02 18:34 UTC, harshavardhana requested changes
Let's not make changes to legacy signature.

2022-08-02 18:34 UTC, harshavardhana commented on pkg/signer/request-signature-v2.go
>  	}
Signature v2 is deprecated use signature v4 @zhutianhao

2022-08-03 03:43 UTC, zhutianhao commented
Although V2 has been deprecated, there are still a few cases where v2 is used.
The following link explains the usage of x-amz-date.

Signing and authenticating REST requests - Amazon Simple Storage Service<https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html>
Time stamp requirement

……

Therefore, if you include the x-amz-date header, use the empty string for the Date when constructing the StringToSign.

……


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月3日 2:34
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [minio/minio-go] Add date if not present and there is no "X-Amz-Date" (PR #1685)


@harshavardhana requested changes on this pull request.

Let's not make changes to legacy signature.


In pkg/signer/request-signature-v2.go<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fminio%2Fminio-go%2Fpull%2F1685%23discussion_r935904967&data=05%7C01%7C%7C949930ceb8344855166b08da74b5a214%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637950620731597143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tpQyy%2FGsek6BNLS0bk%2F31solEVdkkTX%2Bijgoo%2BirsS0%3D&reserved=0>:

> -     // Add date if not present.

-       if date := req.Header.Get("Date"); date == "" {

+       // Add date if not present and there is no "X-Amz-Date".

+       if date := req.Header.Get("Date"); date == ""  && req.Header.Get("X-Amz-Date") == "" {

               req.Header.Set("Date", d.Format(http.TimeFormat))

        }

Signature v2 is deprecated use signature v4 @zhutianhao<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzhutianhao&data=05%7C01%7C%7C949930ceb8344855166b08da74b5a214%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637950620731597143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QfxKD7aYpKnBiWo7ZhnKXOf%2F9NvYHv3Z4fLCSQdssRA%3D&reserved=0>

―
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fminio%2Fminio-go%2Fpull%2F1685%23pullrequestreview-1059248822&data=05%7C01%7C%7C949930ceb8344855166b08da74b5a214%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637950620731597143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=px1PnaRVvdvQmYcoZimYda5nj3H2JXxpyrX6K7QzlxE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABABJC5NZ3WS46UBD7TQRW3VXFS3HANCNFSM55KBMISQ&data=05%7C01%7C%7C949930ceb8344855166b08da74b5a214%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637950620731597143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B7qsvkFedUaf%2BrXka88OY7QR%2BjC8WReCMmJSBSixdeY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-08-04 08:41 UTC, kannappanr commented
I don't see any advantage in adding this code, most of the users of MinIO or any S3 for that matter are not going to use v2 and even if they do, they are not going to set `x-amz-date` header usually. They will expect the SDK to handle this. Even if they do, the SDK additionally sets `Date` header, and `MinIO` will anyway honor just `x-amz-date` header, even if `Date` header is present. So, I think existing code is fine.

2022-09-17 08:47 UTC, harshavardhana commented
Do not have substantial evidence on why this is needed, closing for now.

2022-09-17 08:47 UTC, closed without merging