feat(#1755): GetObject supports overriding response header values
minio/minio-go pull request #1756
Opened 2023-01-16 01:40 UTC by reedchan7

This allows you to pass in the response headers that you need to override when calling the GetObject method.

2023-01-16 02:37 UTC, harshavardhana approved these changes

2023-01-16 08:39 UTC, klauspost commented
Imports missing in the example:

```
# command-line-arguments
Error: ./getobject-override-respheaders.go:36:19: undefined: minio
Error: ./getobject-override-respheaders.go:37:11: undefined: credentials
Error: ./getobject-override-respheaders.go:41:3: undefined: log
Error: ./getobject-override-respheaders.go:50:9: undefined: minio
Error: ./getobject-override-respheaders.go:55:36: undefined: context
Error: ./getobject-override-respheaders.go:57:3: undefined: log
Error: ./getobject-override-respheaders.go:63:3: undefined: log
Error: ./getobject-override-respheaders.go:69:3: undefined: log
Error: ./getobject-override-respheaders.go:72:15: undefined: io
Error: ./getobject-override-respheaders.go:73:3: undefined: log
Error: ./getobject-override-respheaders.go:73:3: too many errors
Error: make: *** [Makefile:27: examples] Error 1
Error: Process completed with exit code 2.
```

2023-01-16 09:12 UTC, reedchan7 commented
> Imports missing in the example:
> 
> ```
> # command-line-arguments
> Error: ./getobject-override-respheaders.go:36:19: undefined: minio
> Error: ./getobject-override-respheaders.go:37:11: undefined: credentials
> Error: ./getobject-override-respheaders.go:41:3: undefined: log
> Error: ./getobject-override-respheaders.go:50:9: undefined: minio
> Error: ./getobject-override-respheaders.go:55:36: undefined: context
> Error: ./getobject-override-respheaders.go:57:3: undefined: log
> Error: ./getobject-override-respheaders.go:63:3: undefined: log
> Error: ./getobject-override-respheaders.go:69:3: undefined: log
> Error: ./getobject-override-respheaders.go:72:15: undefined: io
> Error: ./getobject-override-respheaders.go:73:3: undefined: log
> Error: ./getobject-override-respheaders.go:73:3: too many errors
> Error: make: *** [Makefile:27: examples] Error 1
> Error: Process completed with exit code 2.
> ```

Now fixed 👍

2023-01-16 12:23 UTC, harshavardhana approved these changes

2023-01-16 13:32 UTC, reedchan7 commented
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/49066821/212689692-61f5210b-617d-4c6c-ac62-a10cde89573b.png">

These codes are in my forked repo, not in v7.0.32, how to resolve this issue? @harshavardhana

2023-01-16 16:45 UTC, klauspost commented
@reedchan7 No - you should keep `../..` it replaces it with whatever version it is using. It should be

```
replace github.com/minio/minio-go/v7 v7.0.32 => ../..
```

2023-01-16 16:46 UTC, klauspost requested changes

2023-01-16 16:59 UTC, reedchan7 commented
> @reedchan7 No - you should keep `../..` it replaces it with whatever version it is using. It should be
> 
> ```
> replace github.com/minio/minio-go/v7 v7.0.32 => ../..
> ```

I got it. Thanks  :smile:

2023-01-16 23:36 UTC, harshavardhana approved these changes

2023-01-18 15:11 UTC, klauspost approved these changes
LGTM. Thanks!

2023-01-18 15:35 UTC, merged