Modification documents
minio/minio-go pull request #1794
Opened 2023-03-29 12:22 UTC by cqqqq777

Updated Chinese documents and corrected English documents

2023-03-29 12:26 UTC, cqqqq777 reviewed
Updated Chinese documents and corrected English documents

2023-03-29 12:27 UTC, cqqqq777 reviewed
Chinese documents are based on English documents

2023-03-29 15:58 UTC, harshavardhana requested changes

2023-03-29 15:58 UTC, harshavardhana commented on docs/API.md
> +| [`MakeBucket`](#Ma[API.md](zh_CN%2FAPI.md)keBucket)                           | [`GetObject`](#GetObject)                           | [`PresignedGetObject`](#PresignedGetObject)   | [`SetBucketPoli
There should be no mention of Chinese docs in English

2023-06-12 07:11 UTC, jiuker commented
@cqqqq777 Modify your pr plz.

2023-06-28 21:58 UTC, harshavardhana commented
Stale PR closing.

2023-06-28 21:58 UTC, closed without merging