all the internal data type
minio/minio-go pull request #1849
Opened 2023-07-08 05:44 UTC by harshavardhana

2023-07-08 09:47 UTC, vadmeste approved these changes
LGTM

2023-07-10 09:18 UTC, klauspost requested changes

2023-07-10 09:18 UTC, klauspost commented on examples/minio/listobjectsV2WithMetadata.go
> +	minioClient, err := minio.New("play.min.io", &minio.Options{
```suggestion
	s3Client, err := minio.New("play.min.io", &minio.Options{
```

Maybe provide full credentials.

2023-07-10 21:58 UTC, poornas approved these changes

2023-07-10 23:05 UTC, merged