replication: additional fields for metrics
minio/minio-go pull request #1874
Opened 2023-08-16 15:59 UTC by poornas

2023-08-21 18:57 UTC, harshavardhana approved these changes

2023-08-21 18:59 UTC, harshavardhana requested changes
we simply need to have some validation on the data structure received such that we can avoid panics at runtime.

Add some validation before we can trust the structs, return error early and then we can safely process the stats.

2023-08-21 18:59 UTC, harshavardhana commented on pkg/replication/replication.go
> +	tot.Avg /= float32(len(q.Nodes))
check for situations like `q.Nodes` is zero @poornas to avoid potential crashes if any.

2023-08-21 22:28 UTC, harshavardhana approved these changes

2023-08-21 22:28 UTC, merged

2023-08-23 07:44 UTC, jiuker commented
It broken something to mc. @poornas @harshavardhana