Add Expires to PutObject opts
minio/minio-go pull request #1900
Opened 2023-11-19 00:43 UTC by vadmeste

2023-11-19 01:18 UTC, harshavardhana requested changes
Vulncheck must be set to exact version of Go

2023-11-19 01:18 UTC, harshavardhana commented on .github/workflows/vulncheck.yml
> +        go-version: [ 1.21.x ]
```suggestion
        go-version: [ 1.21.4 ]
```

2023-11-19 01:25 UTC, harshavardhana approved these changes

2023-11-19 01:26 UTC, merged

2023-12-06 12:19 UTC, MB175 commented
I tried using this option but its not working

2023-12-06 13:33 UTC, MB175 commented
@klauspost  I just did it looks like the header is set correctly also the "Expires" field is set. Looks like the issue lies within my minio server which is still serving the file after expiration strange enough.

So no worries your changes work as expected, sorry for the disturbance

2023-12-06 13:42 UTC, klauspost commented
@MB175 The header has no functional meaning other than being stored on the object. It can be picked up by proxies, etc.

MinIO will do nothing more than store it and return whatever value it was set to. It is not a TTL. See [Object Lifecycle Management](https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html#object-expiration) on how to expire objects via lifecycle. This is similar to AWS S3.