New API implementation: GetObjectAttributes
minio/minio-go pull request #1921
Opened 2024-01-02 13:32 UTC by zveinn

This PR is related to another PR in the minio/minio .. (will be updating this description in a few minutes)

2024-01-02 14:19 UTC, klauspost reviewed
IMO you should make this easier to use and abstract away the overly complicated parts (pun not intended, but nice).

2024-01-02 14:19 UTC, klauspost commented on api-get-object-attributes.go
> +// ObjectAttributesOptions ...
...

2024-01-02 14:19 UTC, klauspost commented on api-get-object-attributes.go
> +		Parts                []*struct {
```suggestion
		Parts                []ObjectPart `xml:"Part"`
```

2024-01-02 14:19 UTC, klauspost commented on api-get-object-attributes.go
> +	PartNumberMarker     int
I would kind of expect us to handle these internally and not expose these in the API.

So we just return all parts... I think this is overengineering on AWS' part already. We shouldn't make users bother with these and just return all parts.

2024-01-02 14:19 UTC, klauspost commented on api-get-object-attributes.go
> +		IsTruncated          bool
Again, all of these shouldn't really be exposed.

2024-01-02 14:19 UTC, klauspost commented on api-get-object-attributes.go
> +	ObjectAttributes     string
It should be obvious how to use this SDK without needing to read the API specs. I don't really see any point in the user having to bother with filling this. 

We could accept a mask with named options - but I don't really see much point in filtering.

2024-01-02 16:21 UTC, zveinn commented
> IMO you should make this easier to use and abstract away the overly complicated parts (pun not intended, but nice).

The api has been simplified based on our discussion today, I will double check AWS behavior tomorrow when it comes to large part numbers.

2024-01-02 16:26 UTC, klauspost approved these changes
Just unexport the const. LGTM otherwise.

2024-01-02 16:31 UTC, klauspost requested changes

2024-01-02 16:31 UTC, klauspost commented on api-get-object-attributes.go
> +	objectAttributesResponse
Unexported. Must be available for caller.

2024-01-02 16:31 UTC, klauspost commented on api-get-object-attributes.go
> +		Parts      []*objectPart `xml:"Part"`
Type must be exported.

2024-01-02 16:31 UTC, klauspost commented on api-get-object-attributes.go
> +	defer closeResponse(resp)
Move up after error checking resp.

2024-01-02 17:00 UTC, zveinn commented on api-get-object-attributes.go
> +	headers.Set(amzMaxParts, "0")
Made a comment about that above, will keep this unresolved until I test tomorrow

2024-01-04 14:58 UTC, klauspost commented
@zveinn 

```
Running lint check
Error: api-get-object-attributes.go:65:1: exported: comment on exported type ObjectAttributePart should be of the form "ObjectAttributePart ..." (with optional leading article) (revive)
// ObjectAttributesResponse ...
^
Error: constants.go:63:2: exported: exported const GetObjectAttributesTags should have comment (or a comment on this block) or be unexported (revive)
	GetObjectAttributesTags = "ETag,Checksum,StorageClass,ObjectSize,ObjectParts"
	^
Error: make: *** [Makefile:15: lint] Error 1
```

2024-01-07 11:55 UTC, klauspost commented
@zveinn 

Kinda interesting this gets thrown...

```
{"args":{"bucketName":"minio-go-test-rizxvdf5fd4dqwbk","objectName":"file2","opts":"minio.ObjectAttributesOptions{}"},"duration":6607,"error":"XML syntax error on line 1: invalid UTF-8","function":"GetObjectAttributes(ctx, bucketName, objectName, opts)","message":"GetObjectAttributes failed","name":"minio-go: testGetObjectAttributes","status":"FAIL"}
```

2024-01-07 18:43 UTC, harshavardhana commented on api-get-object-attributes.go
> +package minio
Add missing copyright header.

2024-01-07 19:46 UTC, klauspost reviewed
I guess for older versions it returns the object data?

Kinda clunky API-wise, but I guess AWS overloaded the `GET bucket/object` to implement this...

We should probably document that this is the behavior (if it is) when the API call isn't supported by the remote.. Maybe we should even check the response content type or something similar before decoding.

2024-01-07 19:46 UTC, klauspost commented on api-get-object-attributes.go
> +// ObjectAttributesResponse ...
Fill out.

2024-01-07 19:46 UTC, klauspost commented on api-get-object-attributes.go
> +// ObjectAttributePart ...
Fill out...

2024-01-07 19:46 UTC, klauspost commented on api-get-object-attributes.go
> +// GetObjectAttributes ...
Make this proper documentation. Eg

```suggestion
// GetObjectAttributes provides detailed object information.
```

2024-01-07 20:51 UTC, harshavardhana requested changes

2024-01-07 20:51 UTC, harshavardhana commented on functional_tests.go
> +		testGetObjectAttributesSSECEncryption()
move this inside `if tls` block @zveinn

2024-01-07 21:03 UTC, harshavardhana commented
Something is broken in the tests as well now because in this PR master branch runs fine with MinIO latest release.

```
{"args":{"bucketName":"minio-go-test-riqvc9tscw0inoj5","contentType":"","filePath":"","metadata":"custom/contenttype","objectName":"ugqepx3npjrsgnzcb1940qnoiikd5y","sse":{}},"duration":62,"function":"FPutEncryptedObject(bucketName, objectName, filePath, contentType, sse)","name":"minio-go: testSSES3EncryptionFPut","status":"PASS"}
{"args":{"bucketName":"minio-go-test-t1jmaabgxw9mey3i","objectName":"v33nnuhfn0gdkz1wbqjhmsx3gjn6gx"},"duration":4491,"function":"GetObject(bucketName, objectName)","name":"minio-go: testSSES3EncryptedGetObjectReadAtFunctional","status":"PASS"}
{"args":{"bucketName":"minio-go-test-3v21332559zpfsz4","objectName":"ob2ojnkoranpdpgvf5tsnnqch0vjgc"},"duration":7785,"function":"GetObject(bucketName, objectName)","name":"minio-go: testSSES3EncryptedGetObjectReadSeekFunctional","status":"PASS"}
{"args":{"destination":{"Bucket":"minio-go-test-rplpr2u4nzbis0ct","Object":"srcObject","Encryption":null,"UserMetadata":null,"ReplaceMetadata":false,"UserTags":null,"ReplaceTags":false,"LegalHold":"","Mode":"","RetainUntilDate":"0001-01-01T00:00:00Z","Size":0,"Progress":null},"source":{"Bucket":"minio-go-test-rplpr2u4nzbis0ct","Object":"srcObject","VersionID":"","MatchETag":"","NoMatchETag":"","MatchModifiedSince":"0001-01-01T00:00:00Z","MatchUnmodifiedSince":"0001-01-01T00:00:00Z","MatchRange":false,"Start":0,"End":0,"Encryption":{}}},"duration":262,"function":"CopyObject(destination, source)","name":"minio-go: testEncryptedSSES3ToSSES3CopyObject","status":"PASS"}
{"args":{"destination":{"Bucket":"minio-go-test-9q30ubdszad5fhmk","Object":"srcObject","Encryption":null,"UserMetadata":null,"ReplaceMetadata":false,"UserTags":null,"ReplaceTags":false,"LegalHold":"","Mode":"","RetainUntilDate":"0001-01-01T00:00:00Z","Size":0,"Progress":null},"source":{"Bucket":"minio-go-test-9q30ubdszad5fhmk","Object":"srcObject","VersionID":"","MatchETag":"","NoMatchETag":"","MatchModifiedSince":"0001-01-01T00:00:00Z","MatchUnmodifiedSince":"0001-01-01T00:00:00Z","MatchRange":false,"Start":0,"End":0,"Encryption":{}}},"duration":261,"function":"CopyObject(destination, source)","name":"minio-go: testEncryptedSSES3ToUnencryptedCopyObject","status":"PASS"}
{"args":{"destination":{"Bucket":"minio-go-test-1kleakxixnvtqvnj","Object":"dstObject","Encryption":{},"UserMetadata":null,"ReplaceMetadata":false,"UserTags":null,"ReplaceTags":false,"LegalHold":"","Mode":"","RetainUntilDate":"0001-01-01T00:00:00Z","Size":0,"Progress":null},"source":{"Bucket":"minio-go-test-1kleakxixnvtqvnj","Object":"srcObject","VersionID":"","MatchETag":"","NoMatchETag":"","MatchModifiedSince":"0001-01-01T00:00:00Z","MatchUnmodifiedSince":"0001-01-01T00:00:00Z","MatchRange":false,"Start":0,"End":0,"Encryption":null}},"duration":233,"function":"CopyObject(destination, source)","name":"minio-go: testUnencryptedToSSES3CopyObject","status":"PASS"}
{"args":{},"duration":151,"function":"CopyObjectPart(destination, source)","name":"minio-go: testUnencryptedToSSES3CopyObjectPart","status":"PASS"}
{"args":{},"duration":135,"function":"CopyObjectPart(destination, source)","name":"minio-go: testSSES3EncryptedToUnencryptedCopyPart","status":"PASS"}
{"args":{},"duration":169,"function":"CopyObjectPart(destination, source)","name":"minio-go: testSSES3EncryptedToSSES3CopyObjectPart","status":"PASS"}
```

However this PR is passing GetObjectAttributes but failing in other places.

2024-01-08 14:48 UTC, klauspost approved these changes
Lovely! <3

2024-01-08 19:18 UTC, harshavardhana approved these changes

2024-01-08 19:18 UTC, merged