Added `x-minio-replication-object-size` to allowed headers
minio/minio-go pull request #1946
Opened 2024-03-05 07:37 UTC by shtripat

Need to send actual object size while replicating a multipart object as parts would be replicated as is with their encrypted content and content length. Later at target while creating xl.meta for the completed object, we need the actual object size be set as `X-Minio-Internal-actual-size`

2024-03-05 07:45 UTC, harshavardhana requested changes

2024-03-05 07:45 UTC, harshavardhana commented on utils.go
> +	"x-minio-replication-object-size":                           true,
```suggestion
	"x-minio-replication-actual-object-size":                           true,
```

2024-03-10 14:12 UTC, klauspost approved these changes

2024-03-10 21:10 UTC, harshavardhana approved these changes

2024-03-10 21:11 UTC, merged